baseURL: "https://purple-screen.com/"
languageCode: en-us
title: PurpleScreen
theme: lanyon
canonifyurls: true
#pygmentsCodeFences: true
#pygmentsUseClassic: true
#pygmentsUseClasses: true
preserveTaxonomyNames: true
taxonomies:
#  category: categories
  tag: tags
publishDir: docs
googleAnalytics: UA-47057839-1
permalinks:
    post: ":year/:month/:day/:title/"
    fixed: ":title/"
params:
    Title: PurpleScreen
    #linkedinName = 'alexeymiasoedov'
    Tagline: '>> sudo make read'
    utterances:
        repo: akamac/purple-screen
