baseURL: "https://purple-screen.com/"
languageCode: en-us
title: Blog
theme: lanyon
canonifyurls: true
#pygmentsCodeFences: true
#pygmentsUseClassic: true
#pygmentsUseClasses: true
publishDir: docs
permalinks:
    post: ":year/:month/:day/:title/"
    fixed: ":title/"
params:
    Title: PurpleScreen
    #linkedinName = 'alexeymiasoedov'
    Tagline: blog about open source
    utterances:
        repo: akamac/purple-screen